spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderdatabase
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format:
          sql: true
  cloud:
    config:
      uri: http://localhost:8888
      
      
microservice:
  ORDER-SERVICE:
     endpoints:
        endpoint:
         uri: http://ORDER-SERVICE/order/bookorder 
  PAYMENT-SERVICE:
     endpoints:
        endpoint:
         uri: http://PAYMENT-SERVICE/payment/dopayment


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
